### ISSUE TITLE
Execution errors after "Combining regions".

### ISSUE THREAD

**Issue by JonatanFernandez** [Dowell-Lab/TFEA#17]
Hello! First time user here, I am trying to execute the following script (2 conditions, 4 vs 4 samples)

```shell
TFEA --output ./8.TFEA/TFEA_output/ \
--bed1 ./3.Aligned_reads/mtb1.bed ./3.Aligned_reads/mtb2.bed ./3.Aligned_reads/mtb3.bed ./3.Aligned_reads/mtb4.bed \
--bed2 ./3.Aligned_reads/DMSO1.bed ./3.Aligned_reads/DMSO2.bed ./3.Aligned_reads/DMSO3.bed ./3.Aligned_reads/DMSO4.bed \
--bam1 ./3.Aligned_reads/mtb1.BAM ./3.Aligned_reads/mtb2.BAM ./3.Aligned_reads/mtb3.BAM ./3.Aligned_reads/mtb4.BAM \
--bam2 ./3.Aligned_reads/DMSO1.BAM ./3.Aligned_reads/DMSO2.BAM ./3.Aligned_reads/DMSO3.BAM ./3.Aligned_reads/DMSO4.BAM \
--label1 MTBr --label2 DMSO \
--genomefasta ./2.Genome/GRCm39.fasta \
--fimo_motifs ../TFEA/test/test_files/test_database.meme
```

And got the folllowing output, with a IndexError in the traceback... 

```console
./TFEA.sh 
User arguments verified, all required inputs present and not conflicting.
TFEA start: 
Combining Regions... Traceback (most recent call last):
  File "/home/joni/.local/lib/python3.8/site-packages/TFEA/combine.py", line 381, in mumerge
    subprocess.check_output(mumerge_command, stderr=subprocess.PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', PosixPath('/home/joni/.local/lib/python3.8/site-packages/TFEA/mumerge.py'), '-i', PosixPath('8.TFEA/TFEA_output/temp_files/mumerge_input.txt'), '-o', PosixPath('8.TFEA/TFEA_output/temp_files/combined_file.mumerge')]' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joni/.local/bin/TFEA", line 4, in <module>
    main.run()
  File "/home/joni/.local/lib/python3.8/site-packages/TFEA/main.py", line 128, in run
    combine.main()
  File "/home/joni/.local/lib/python3.8/site-packages/TFEA/combine.py", line 117, in main
    combined_file = mumerge(mumerge_input, combined_file, bed1=bed1, 
  File "/home/joni/.local/lib/python3.8/site-packages/TFEA/combine.py", line 383, in mumerge
    raise exceptions.SubprocessError(e.stderr.decode())
TFEA.exceptions.SubprocessError: Killed
cat: write error: Broken pipe
Traceback (most recent call last):
  File "/home/joni/.local/lib/python3.8/site-packages/TFEA/mumerge.py", line 815, in <module>
    merge_regions = bedfile_reader(union_bedfile,
  File "/home/joni/.local/lib/python3.8/site-packages/TFEA/mumerge.py", line 308, in bedfile_reader
    while line[0] == '#':
IndexError: string index out of range
```

Any ideas? Thanks in advance.

**Comment by jtstanley** [comment]
Hey @JonatanFernandez, a few things to get a better idea of your inputs:

1) Does it output the input file formatted for muMerge (should be called something like `mumerge_input.txt`)?
2) It might be hitting an empty string in one of your bed files (`mumerge.py` line 308). Can you `head` and `tail` your input bed files? Is there a blank line somewhere (probably at the end)?

**Comment by JonatanFernandez** [comment]
Hello @jtstanley, thank you so much for your reply.

Indeed, it outputs `numerge_input.txt` in the temp_files folder:
[mumerge_input.txt](https://github.com/Dowell-Lab/TFEA/files/7149388/mumerge_input.txt)

I did head/tails of all the bed files (attached) but I haven't appreaciated any blank line..
[headsandtails.txt](https://github.com/Dowell-Lab/TFEA/files/7149385/headsandtails.txt)

**Comment by JonatanFernandez** [comment]
So, I tried different things:

-I suspected it might had something to do with the meme suite, checked perl packages, updated to newest version of the meme package (5.4.1). Passed all tests before making install..
-All TFEA tests pass as well...

`
> TFEA --test-install
test_bedtools (__main__.TestMain) ... ok
test_deseq (__main__.TestMain) ... ok
test_deseq2 (__main__.TestMain) ... ok
test_fasta_markov (__main__.TestMain) ... ok
test_fimo (__main__.TestMain) ... ok
test_imagemagick (__main__.TestMain) ... ok
test_meme (__main__.TestMain) ... ok
test_meme2images (__main__.TestMain) ... ok
test_python_packages (__main__.TestMain) ... ok

----------------------------------------------------------------------
Ran 9 tests in 11.307s

OK


> TFEA --test-full
test_full (__main__.TestMain) ... 
============================================
User arguments verified, all required inputs present and not conflicting.
TFEA start: 
(CPU: 0.0%)
(Memory Usage: 13.9KB)
Combining Regions... done in: 0:00:15 . Processing 415 regions
(CPU: 12.7%)
(Memory Usage: 28.1KB)
Ranking regions...
	Generating Meta-Profile per Quartile:
	 Completed: 4/4  
done in: 0:00:24
(CPU: 12.8%)
(Memory Usage: 352.3KB)
Scanning regions using fimo...
	TFEA:
	 Completed: 4/4  (CPU: 12.9%) (Memory Usage: 352.3KB) 
	MD:
	 Completed: 4/4  (CPU: 13.1%) (Memory Usage: 352.3KB) 
	 Completed: 4/4  (CPU: 15.3%) (Memory Usage: 352.3KB) 
	MDD:
	 Completed: 4/4  (CPU: 12.4%) (Memory Usage: 352.3KB) 
	 Completed: 4/4  (CPU: 21.1%) (Memory Usage: 352.3KB) 
done in: 0:00:02
(CPU: 0.0%)
(Memory Usage: 352.3KB)
Calculating enrichment...
	Correcting GC:
	 Completed: 4/4  (CPU: 0.0%) (Memory Usage: 352.3KB)  
	Calculating E-Score:
	 convert-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
	 convert-im6.q16: no images defined `/home/user/.local/lib/python3.8/site-packages/TFEA/test/test_files/test_output/plots/logoSP2_HUMAN_H11MO_0_A.png' @ error/convert.c/ConvertImageCommand/3258.
	 
	 Completed: 0/4  /home/user/.local/lib/python3.8/site-packages/TFEA/plot.py:781: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels(['0','0.2','0.4','0.6','0.8','1'])
	 Completed: 1/4  	 convert-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
	 convert-im6.q16: no images defined `/home/user/.local/lib/python3.8/site-packages/TFEA/test/test_files/test_output/plots/logoTBX1_HUMAN_H11MO_0_D.png' @ error/convert.c/ConvertImageCommand/3258.
	 
(CPU: 12.7%) (Memory Usage: 793.9KB) /home/user/.local/lib/python3.8/site-packages/TFEA/plot.py:781: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels(['0','0.2','0.4','0.6','0.8','1'])
	 Completed: 2/4  	 convert-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
	 convert-im6.q16: no images defined `/home/user/.local/lib/python3.8/site-packages/TFEA/test/test_files/test_output/plots/logoSOX10_HUMAN_H11MO_0_B.png' @ error/convert.c/ConvertImageCommand/3258.
	 
(CPU: 13.0%) (Memory Usage: 793.9KB) /home/user/.local/lib/python3.8/site-packages/TFEA/plot.py:781: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels(['0','0.2','0.4','0.6','0.8','1'])
	 Completed: 3/4  	 convert-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
	 convert-im6.q16: no images defined `/home/user/.local/lib/python3.8/site-packages/TFEA/test/test_files/test_output/plots/logoZN121_HUMAN_H11MO_0_C.png' @ error/convert.c/ConvertImageCommand/3258.
	 
(CPU: 12.9%) (Memory Usage: 794.7KB) /home/user/.local/lib/python3.8/site-packages/TFEA/plot.py:781: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels(['0','0.2','0.4','0.6','0.8','1'])
	 Completed: 4/4  (CPU: 13.2%) (Memory Usage: 795.2KB) 
	MD:
	 Completed: 4/4  (CPU: 0.0%) (Memory Usage: 795.2KB)  
	MDD:
	 Completed: 4/4  (CPU: 0.0%) (Memory Usage: 795.2KB) 
done in: 0:00:40
(CPU: 9.1%)
(Memory Usage: 795.2KB)
Creating output... done in: 0:00:03
(CPU: 12.7%)
(Memory Usage: 795.2KB)
TFEA done. Output in: /home/user/.local/lib/python3.8/site-packages/TFEA/test/test_files/test_output
ok

----------------------------------------------------------------------
Ran 1 test in 86.656s

OK
`

-I run TFEA on a completely different set of files (new experiment, both BAMs and BEDs). I still got the same error.
-I run it with only 1 file per condition...
- I removed posible whitespaces from BED file using... 
`for file in *.BED
do
	ext=.BED;
    fname=`basename $file $ext`;
    echo "Current BED: $fname";
	cat ${file} | tr -d " " > ${fname}_rs.BED
done`

BEDs seem to be alright otherwise...

**Comment by fisst** [comment]
Hei,
 try to use e.g. --combine mergeall
This let me go some steps further in the script....

Maybe later on mumerge.py might work.

best
stefan
