### ISSUE TITLE
Cannot open hg38.fa downloaded from UCSC

### ISSUE THREAD

**Issue by c2b2pss** [Dowell-Lab/TFEA#25]
So I was able to figure out stuff and run the program.  However, I get
stuck at not being able to open the genome annotation hg38.fa file I
downloaded from UCSC Website. IS there a speficifc format required, or
a specific compilation?
 
ERROR:
 
TFEA --config '/home/premsubramaniam/Desktop/TFEA_output/Untitled.ini'
User arguments verified, all required inputs present and not
conflicting.
TFEA start:
Combining Regions... done in: 0:49:29 . Processing 416763 regions
Ranking regions...
done in: 0:29:18
Scanning regions using fimo...
Traceback (most recent call last):
  File "/home/premsubramaniam/.local/lib/python3.9/site-
packages/TFEA/scanner.py", line 457, in getfasta
    subprocess.run(getfasta_command, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bedtools', 'getfasta', '-fi',
PosixPath('/home/premsubramaniam/Dropbox/lncap ATACSeq
retry/lncap/hg38.fa'), '-bed',
PosixPath('/home/premsubramaniam/Desktop/TFEA_output/temp_files/ranked_
file.bed'), '-fo',
PosixPath('/home/premsubramaniam/Desktop/TFEA_output/temp_files/ranked_
file.fa')]' returned non-zero exit status 1.
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/premsubramaniam/.local/bin/TFEA", line 4, in <module>
    main.run()
  File "/home/premsubramaniam/.local/lib/python3.9/site-
packages/TFEA/main.py", line 148, in run
    scanner.main()
  File "/home/premsubramaniam/.local/lib/python3.9/site-
packages/TFEA/scanner.py", line 159, in main
    fasta_file = getfasta(bedfile=ranked_file, genomefasta=genomefasta,
  File "/home/premsubramaniam/.local/lib/python3.9/site-
packages/TFEA/scanner.py", line 461, in getfasta
    raise exceptions.SubprocessError(e.stderr.decode())
TFEA.exceptions.SubprocessError: Error: The requested fasta database
file (/home/premsubramaniam/Dropbox/lncap ATACSeq retry/lncap/hg38.fa)
could not be opened. Exiting!

**Comment by Hope2925** [comment]
We recommend downloading the file -- if the file is a link rather than the actual file and the file is massive, it may not work.
