### ISSUE TITLE
error with meme file format 

### ISSUE THREAD

**Issue by archanabhardwaj** [Dowell-Lab/TFEA#28]
Hello 

TFEA is really nice method to explore the motifs in sequencing data. I would like to use TFEA on my ranked gene list. I tried test data and followed these steps : 

## With test data which I downloaded from 

> wget https://raw.githubusercontent.com/Dowell-Lab/TFEA/master/TFEA/test/test_files/test_ranked_file.bed
> wget https://raw.githubusercontent.com/Dowell-Lab/TFEA/master/TFEA/test/test_files/test_database.meme
> wget 'https://github.com/Dowell-Lab/TFEA/blob/master/TFEA/test/test_files/chr22.fa?raw=true' -O chr22.fa
> wget https://raw.githubusercontent.com/Dowell-Lab/TFEA/master/TFEA/test/test_files/chr22.fa.fai

**> TFEA --output test_output --ranked_file test_ranked_file.bed --genomefasta chr22.fa --fimo_motifs test_database.meme**
User arguments verified, all required inputs present and not conflicting.
TFEA start: 
Scanning regions using fimo...
	TFEA:
	 Completed: 0/4  Traceback (most recent call last):
  File "/home/archana/.local/bin/TFEA", line 4, in <module>
    main.run()
  File "/home/archana/.local/lib/python3.8/site-packages/TFEA/main.py", line 148, in run
    scanner.main()
  File "/home/archana/.local/lib/python3.8/site-packages/TFEA/scanner.py", line 220, in main
    motif_distances = multiprocess.main(function=fimo, args=motif_list, 
  File "/home/archana/.local/lib/python3.8/site-packages/TFEA/multiprocess.py", line 74, in main
    x = function(arg, **kwargs)
  File "/home/archana/.local/lib/python3.8/site-packages/TFEA/scanner.py", line 594, in fimo
    distances = fimo_parse_stdout(fimo_stdout=fimo_out, 
  File "/home/archana/.local/lib/python3.8/site-packages/TFEA/scanner.py", line 701, in fimo_parse_stdout
    name_index = header.index('sequence_name')
ValueError: 'sequence_name' is not in list

**Even, I also tried different meme database files, but always gives me same error.** 
TFEA --output test_output --ranked_file test_ranked_file.bed --genomefasta chr22.fa --fimo_motifs HOCOMOCOv11_full_MOUSE_mono_meme_format.mem
 
I tried to fix the space issue by replacing special character as mentioned in https://github.com/Dowell-Lab/TFEA/issues/14 still can not fix this issue. 

It would be great if you can help me to fix it.

**Comment by biomaral** [comment]
Hello, I know it is super late now to reply this question. You already analyzed all the data by now. But for the future for those they are facing this problem now: This error migh be related to the format of the Memes or how update it is. after using the version of 5.2.2 of the Meme package, I didnot have any problem
